### ISSUE TITLE
Make Logo For The Game

### ISSUE THREAD

**Issue by DobbyK** [DobbyK/Heartlife#4]
Should be under /sprites to replace the basic text image. Doesn't need to be done to continue. Should have to do with game theme around hearts. Must be under 800 by 600. Thank You.

**Comment by DobbyK** [comment]
![heartlife_logo_v2](https://user-images.githubusercontent.com/69256884/98759361-2c454f00-238e-11eb-9e51-7fa8ea653171.png)
Make Do logo, will update code in next patch. Credit to @megaoy

**Comment by megaoy** [comment]
as requested in the inssue i made the logo, this is temporary solution as later on i will make one that represents better the game, "logo data.txt" explain the files information
